image: couchdb

before_script:
  - apt-get update -qq && apt-get install -y -qq nodejs npm
  - npm install 
  - npm install -g grunt-cli
#  - npm run start:c9

after_script:
#  - npm run stop:c9

build:
  script:
    - grunt couch-compile

deploy:
  script:
    - grunt couch-deploy
