
image: couchdb

before_script:
  - curl -sL https://deb.nodesource.com/setup_7.x  | sudo -E bash -
  - apt-get update -qq && apt-get install -y -qq nodejs npm
  - ln -s /usr/bin/nodejs /usr/bin/node
  - npm install -g grunt-cli
  - npm install 
  #- npm run start:c9

after_script:
  - npm run stop:c9

build:
  script:
    #- grunt jshint
    - grunt couch-compile

test:
  script:
    - npm run start:c9
    - grunt couch-push:dev
    - grunt test

deploy:
  only: 
    - master
  environment: production
  script:
    - grunt couch-push:prod
