// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Firehall {
	
	
	public partial class Default {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Panel AuthenticatedMessagePanel;
		
		protected System.Web.UI.WebControls.Label WelcomeBackMessage;
		
		protected System.Web.UI.WebControls.Panel AnonymousMessagePanel;
		
		protected System.Web.UI.WebControls.HyperLink lnkLogin;
	}
}
