// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Firehall {
	
	
	public partial class Site {
		
		protected System.Web.UI.HtmlControls.HtmlHead Head1;
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder MainContent;
		
		protected System.Web.UI.WebControls.ContentPlaceHolder LoginContent;
		
		protected System.Web.UI.WebControls.LoginView LoginView1;
		
		protected System.Web.UI.WebControls.LoginName LoginName1;
		
		protected System.Web.UI.WebControls.LoginStatus LoginStatus1;
	}
}
