// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Firehall {
	
	
	public partial class Transaction {
		
		protected System.Web.UI.WebControls.Content MainContentContent;
		
		protected System.Web.UI.WebControls.Label lblId;
		
		protected System.Web.UI.WebControls.TextBox Id;
		
		protected System.Web.UI.WebControls.Label lblDate;
		
		protected System.Web.UI.WebControls.TextBox Date;
		
		protected System.Web.UI.WebControls.Label lblComment;
		
		protected System.Web.UI.WebControls.TextBox Comment;
	}
}
