// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Firehall {
	
	
	public partial class CreatingUserAccounts {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.CreateUserWizard RegisterUser;
		
		protected System.Web.UI.WebControls.CreateUserWizardStep CreateUserStep1;
		
		protected System.Web.UI.WebControls.WizardStep SpecifyRolesStep;
		
		protected System.Web.UI.WebControls.CheckBoxList RoleList;
		
		protected System.Web.UI.WebControls.CompleteWizardStep CompletedStep1;
	}
}
