// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Firehall.Administration.Members {
	
	
	public partial class UserRoles {
		
		protected System.Web.UI.WebControls.Content MainContentContent;
		
		protected System.Web.UI.WebControls.Label ActionStatus;
		
		protected System.Web.UI.WebControls.DropDownList UserList;
		
		protected System.Web.UI.WebControls.Repeater UsersRoleList;
		
		protected System.Web.UI.WebControls.CheckBox RoleCheckBox;
	}
}
