// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Firehall {
	
	
	public partial class Catches {
		
		protected System.Web.UI.WebControls.Content LoginContentContent;
		
		protected System.Web.UI.WebControls.Content MainContentContent;
		
		public new Firehall.Site Master {
			get {
				return ((Firehall.Site)(base.Master));
			}
		}
	}
}
