// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Firehall {
	
	
	public partial class Trips {
		
		protected System.Web.UI.WebControls.Content MainContentContent;
		
		protected System.Web.UI.WebControls.GridView TripGrid;
		
		protected System.Web.UI.WebControls.HyperLink ViewButton;
		
		protected System.Web.UI.WebControls.Label StartTime;
		
		protected System.Web.UI.WebControls.Label FinishTime;
		
		protected System.Web.UI.WebControls.Label Duration;
		
		protected System.Web.UI.WebControls.Label Fisherman;
	}
}
