// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Firehall {
	
	
	public partial class Trip {
		
		protected System.Web.UI.WebControls.Content MainContentContent;
		
		protected AjaxControlToolkit.ToolkitScriptManager ScriptManager1;
		
		protected System.Web.UI.WebControls.Repeater Messages;
		
		protected System.Web.UI.WebControls.Button btnSave;
		
		protected System.Web.UI.WebControls.Button btnCatch;
		
		protected System.Web.UI.WebControls.Button btnChangeRig;
		
		protected System.Web.UI.WebControls.Label lblTripDate;
		
		protected System.Web.UI.WebControls.TextBox txtTripDate;
		
		protected AjaxControlToolkit.CalendarExtender ajaxTripDate;
		
		protected System.Web.UI.WebControls.Label lblTripStart;
		
		protected System.Web.UI.WebControls.TextBox txtTripStart;
		
		protected System.Web.UI.WebControls.Label lblTripEnd;
		
		protected System.Web.UI.WebControls.TextBox txtTripEnd;
		
		protected System.Web.UI.WebControls.Label lblTripDuration;
		
		protected System.Web.UI.WebControls.TextBox TripDuration;
		
		protected System.Web.UI.WebControls.Label lblMap;
		
		protected System.Web.UI.WebControls.Label lblFriends;
		
		protected System.Web.UI.WebControls.Label lblCatches;
		
		protected System.Web.UI.WebControls.TextBox Time;
		
		protected System.Web.UI.WebControls.TextBox Species;
		
		protected System.Web.UI.WebControls.TextBox Length;
		
		protected System.Web.UI.WebControls.TextBox Weight;
		
		protected System.Web.UI.WebControls.Label lblRig;
		
		protected System.Web.UI.WebControls.TextBox Time_1;
		
		protected System.Web.UI.WebControls.TextBox Rig_1;
		
		protected System.Web.UI.WebControls.TextBox Time_2;
		
		protected System.Web.UI.WebControls.TextBox Rig_2;
	}
}
