// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Firehall {
	
	
	public partial class Trip {
		
		protected System.Web.UI.WebControls.Content MainContentContent;
		
		protected System.Web.UI.WebControls.Button Save;
		
		protected System.Web.UI.WebControls.Label lblTripStart;
		
		protected System.Web.UI.WebControls.TextBox TripStart;
		
		protected System.Web.UI.WebControls.Label lblTripEnd;
		
		protected System.Web.UI.WebControls.TextBox TripEnd;
		
		protected System.Web.UI.WebControls.Label lblRoute;
		
		protected System.Web.UI.WebControls.Repeater Route;
		
		protected System.Web.UI.WebControls.TextBox lat;
		
		protected System.Web.UI.WebControls.TextBox @long;
	}
}
