// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Firehall {
	
	
	public partial class CreatingUserAccounts {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.TextBox Username;
		
		protected System.Web.UI.WebControls.TextBox Password;
		
		protected System.Web.UI.WebControls.TextBox Email;
		
		protected System.Web.UI.WebControls.Label SecurityQuestion;
		
		protected System.Web.UI.WebControls.TextBox SecurityAnswer;
		
		protected System.Web.UI.WebControls.Button CreateAccountButton;
		
		protected System.Web.UI.WebControls.Label CreateAccountResults;
	}
}
