// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Firehall {
	
	
	public partial class ManageRoles {
		
		protected System.Web.UI.WebControls.Content MainContentContent;
		
		protected System.Web.UI.WebControls.TextBox RoleName;
		
		protected System.Web.UI.WebControls.Label MessageBox;
		
		protected System.Web.UI.WebControls.Button CreateRoleButton;
		
		protected System.Web.UI.WebControls.GridView RoleList;
		
		protected System.Web.UI.WebControls.Label RoleNameLabel;
	}
}
