// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Firehall.Administration.Roles {
	
	
	public partial class RoleCapabilities {
		
		protected System.Web.UI.WebControls.Content MainContentContent;
		
		protected System.Web.UI.WebControls.Label RoleName;
		
		protected System.Web.UI.WebControls.Repeater CapabilityList;
		
		protected System.Web.UI.WebControls.CheckBox CapabilityCheckBox;
	}
}
