// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Firehall {
	
	
	public partial class UsersAndRoles {
		
		protected System.Web.UI.WebControls.Content MainContentContent;
		
		protected System.Web.UI.WebControls.Label ActionStatus;
		
		protected System.Web.UI.WebControls.DropDownList UserList;
		
		protected System.Web.UI.WebControls.Repeater UsersRoleList;
		
		protected System.Web.UI.WebControls.CheckBox RoleCheckBox;
		
		protected System.Web.UI.WebControls.DropDownList RoleList;
		
		protected System.Web.UI.WebControls.GridView RolesUserList;
		
		protected System.Web.UI.WebControls.Label UserNameLabel;
		
		protected System.Web.UI.WebControls.TextBox UserNameToAddToRole;
		
		protected System.Web.UI.WebControls.Button AddUserToRoleButton;
	}
}
